{
  config,
  lib,
  ...
}: {
  options.user.programs.cmus = {
    enable = lib.mkEnableOption "cmus music player";
  };

  config = lib.mkIf config.user.programs.cmus.enable {
    # cmus rc configuration with wallust colorscheme
    usr.files.".config/cmus/rc".text = ''
      # cmus configuration - auto-generated by NixOS
      # Theme: Wallust Auto (colors update when wallust colorscheme changes)
      colorscheme wallust-auto

      # Add any other cmus settings below
    '';
  };
}
