# This file was generated by npins. Do not modify!
#
# For help, see: https://github.com/andir/npins
let
  data = builtins.fromJSON (builtins.readFile ./sources.json);

  # fetchTarball version that is compatible between all the sources regardless of type
  fetchTarball = source: let
    spec =
      if source.type == "Git"
      then {inherit (source) url hash;}
      else if source.type == "GitRelease"
      then {inherit (source) url hash;}
      else if source.type == "PyPi"
      then {inherit (source) url hash;}
      else if source.type == "Channel"
      then {inherit (source) url hash;}
      else throw "Unknown source type ${source.type}";
  in
    builtins.fetchTarball spec;
in
  builtins.mapAttrs (_: fetchTarball) data.pins
