# Hardware configuration for y0usaf-server
# NOTE: This will be regenerated after nixos-anywhere installation with btrfs layout
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd.availableKernelModules = ["xhci_pci" "ahci" "sd_mod"];
    initrd.kernelModules = [];
    kernelModules = ["kvm-intel"];
    extraModulePackages = [];
    kernel.sysctl."vm.swappiness" = 100;
  };

  # Filesystems are managed by disko.nix during installation
  # After installation, these will be regenerated by nixos-generate-config
  # Temporarily commented out to avoid conflicts with disko
  # fileSystems."/" = {
  #   device = "/dev/disk/by-uuid/f02825db-5bdc-42b7-a5fa-2eb0ec6494d4";
  #   fsType = "ext4";
  # };
  #
  # fileSystems."/boot" = {
  #   device = "/dev/disk/by-uuid/E443-BCEE";
  #   fsType = "vfat";
  # };

  zramSwap = {
    enable = true;
    memoryPercent = 50;
    algorithm = "zstd";
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
