# Phase-3 service parity for the bare-metal finix trial: run the server's
# real services against the real NixOS state (bind-mounted from /persist),
# so a trial boot is a faithful dress rehearsal rather than a toy.
#
# Intentionally NOT ported (dropped from the server altogether):
#   - docker/podman
#   - anything jellyfin-related (the @jellyfin subvol is just data)
#
# State-sharing notes (trial writes to the SAME state NixOS uses):
#   - postgresql is pinned to major 16 to match the on-disk cluster at
#     /persist/var/lib/postgresql/16 (NixOS runs 16.14).
#   - forgejo reuses its NixOS state dir as-is; app.ini + secret files were
#     generated by the NixOS module into custom/conf/ and are pointed at via
#     the same FORGEJO__*__FILE env vars systemd uses (uid/gid 993/989 are
#     pinned on both sides).
#   - n8n state was written by a systemd DynamicUser; a boot task re-chowns
#     it to the trial's static n8n user. systemd re-adopts it on return.
#   - sshd reuses the NixOS host keys from /persist/etc/ssh, so .66 keeps a
#     stable host identity across NixOS<->finix jumps (ends key churn).
#   - syncthing runs as y0usaf against ~/.config/syncthing on @home: same
#     device ID, same folders.
#
# Requires (wired up in finix/default.nix): finix modules cron, nftables,
# postgresql.
{
  config,
  lib,
  pkgs,
  ...
}: let
  # Same disk as server-trial.nix.
  diskUuid = "9dfc38c4-5c75-471d-9106-80ff9175ab92";

  # finix's finit/mount.nix only creates (initrd) mount tasks for
  # neededForBoot filesystems - everything else lands in /etc/fstab and is
  # never mounted (see NOTES.md). Flag every mount here.
  subvol = name: opts: {
    device = "/dev/disk/by-uuid/${diskUuid}";
    fsType = "btrfs";
    options = ["subvol=${name}"] ++ opts;
    neededForBoot = true;
  };

  # Bind service state out of /persist. mount.nix orders binds after their
  # source mount and mkdirs mountpoints (X-mount.mkdir), so these are safe.
  # fsType must be a real filesystem: finix's boot/initrd.nix enables
  # supportedFilesystems.<fsType> for every neededForBoot mount, and the
  # default "auto" is not a valid option there (mount.nix ignores fsType
  # for binds anyway). TODO: report upstream.
  persistBind = dir: {
    device = "/persist${dir}";
    fsType = "btrfs";
    options = ["bind"];
    neededForBoot = true;
  };
  # finit's `environment` option owns the service env file, so the runtime
  # public-IP env (written by the mediamtx-env task) is sourced here rather
  # than via the finit `env:` stanza.
  # NixOS firewall parity: host.nix allowed TCP 80/443/2222/3000/22000 +
  # forgejo 3000/2222, n8n openFirewall (5678), mediamtx 4200, syncthing
  # 22000/21027, tailscale 41641; tailscale0 is trusted.
in {
  ## Storage: server subvolumes + service state bound out of /persist.
  fileSystems = {
    "/home" = subvol "@home" ["compress=zstd" "noatime"];
    "/home/y0usaf/Music" = subvol "@music" [];
    "/home/y0usaf/DCIM" = subvol "@dcim" [];
    "/home/y0usaf/Pictures" = subvol "@pictures" [];
    # Top-level volume for btrbk (snapshot source + _snapshots dir).
    "/btrfs" = {
      device = "/dev/disk/by-uuid/${diskUuid}";
      fsType = "btrfs";
      options = ["subvolid=5"];
      neededForBoot = true;
    };

    "/var/lib/forgejo" = persistBind "/var/lib/forgejo";
    "/var/lib/postgresql" = persistBind "/var/lib/postgresql";
    "/var/lib/private" = persistBind "/var/lib/private"; # n8n
    "/var/lib/tailscale" = persistBind "/var/lib/tailscale";
    "/var/lib/btrbk" = persistBind "/var/lib/btrbk";
  };

  boot.kernelModules = [
    "tun" # tailscaled
    "nf_tables" # don't rely on autoloading for the firewall
  ];

  ## Stable host identity: reuse the NixOS host key (mounted with /persist
  ## in the initrd, so it exists before sshd starts). ed25519 only: finix
  ## renders list settings space-joined on ONE HostKey line, which sshd
  ## rejects - one key per list is the safe shape. TODO: report upstream.
  services = {
    openssh.settings = {
      # Parity with the NixOS universe: real sshd on 2200 (2222 = forgejo,
      # tailnet :22 = Tailscale SSH rescue path).
      Port = [2200];
      HostKey = lib.mkForce [
        "/persist/etc/ssh/ssh_host_ed25519_key"
      ];
    };
    nftables = {
      enable = true;
      configFile = pkgs.writeText "finix-server.nft" ''
        flush ruleset

        table inet filter {
          chain input {
            type filter hook input priority filter; policy drop;

            iifname "lo" accept
            iifname "tailscale0" accept comment "tailnet peers are authenticated"
            ct state established,related accept
            ct state invalid drop
            meta l4proto { icmp, ipv6-icmp } accept

            udp sport 67 udp dport 68 accept comment "dhcpcd lease traffic"

            tcp dport { 80, 443, 2222, 3000, 5678, 22000, 4200 } accept comment "sshd(2200) is tailnet-only"
            udp dport { 21027, 22000, 4200, 41641 } accept
          }
          chain forward {
            type filter hook forward priority filter; policy drop;
          }
        }
      '';
    };
    postgresql = {
      enable = true;
      package = pkgs.postgresql_16;
      authentication = ''
        local all all peer
      '';
    };
    cron.enable = true;
  };
  # Upstream task generates a throwaway key in /var/lib/sshd; sshd's start
  # condition depends on it. Repurpose it as a sanity check on the persisted
  # key instead.
  finit.tasks.ssh-keygen.command = lib.mkForce (pkgs.writeShellScript "check-host-keys" ''
    export PATH=${lib.makeBinPath [pkgs.coreutils]}
    [ -s /persist/etc/ssh/ssh_host_ed25519_key ]
  '');

  ## Firewall (parity with the NixOS server's networking.firewall).

  ## Tailnet names (parity with modules/core/services/tailscale/hosts.nix).
  networking.hosts = {
    "100.105.204.116" = ["forgejo" "syncthing-server"];
    "100.90.54.18" = ["syncthing-desktop"];
  };

  ## Service users. forgejo's uid/gid are pinned to match the NixOS side
  ## (see modules/core/services/forgejo.nix); the rest own no persistent
  ## state (n8n's is re-chowned at boot) so auto-allocated ids are fine.
  users = {
    users = {
      forgejo = {
        isSystemUser = true;
        uid = 993;
        group = "forgejo";
        home = "/var/lib/forgejo";
      };
      n8n = {
        isSystemUser = true;
        group = "n8n";
        home = "/var/lib/private/n8n";
      };
      mediamtx = {
        isSystemUser = true;
        group = "mediamtx";
      };
      nginx = {
        isSystemUser = true;
        group = "nginx";
      };
    };
    groups = {
      forgejo.gid = 989;
      n8n = {};
      mediamtx = {};
      nginx = {};
    };
  };

  ## postgresql (finix upstream module). Pinned to the on-disk cluster's
  ## major version; initdb is skipped because PG_VERSION already exists.

  ## cron backend for scheduled tasks (btrbk).
  providers.scheduler = {
    backend = "cron";
    tasks.btrbk-snapshots = {
      interval = "daily";
      command = "${lib.getExe pkgs.btrbk} -q -c ${pkgs.writeText "btrbk.conf" ''
        timestamp_format long
        snapshot_preserve_min 2d
        snapshot_preserve 7d 4w

        volume /btrfs
          snapshot_dir _snapshots
          subvolume @dcim
          subvolume @music
      ''} run";
    };
  };

  finit.tmpfiles.rules = [
    "d /run/tailscale 0755 root root"
    "d /run/nginx 0755 root root"
  ];

  finit.tasks = {
    # Tailscale SSH is the sshd/PAM/key-independent rescue path (tailscaled
    # itself answers :22 on the tailnet; auth = tailnet identity). The pref
    # lives in the shared /var/lib/tailscale state, but re-assert it every
    # boot so a state reset or a `tailscale up` without --ssh can never
    # silently drop the lifeline. Client side: `ssh rescue` / `ssh
    # rescue-root` from the desktop (modules/user-services/ssh.nix).
    tailscale-ssh = {
      description = "assert tailscale SSH rescue path";
      conditions = ["net/lo/up"];
      command = pkgs.writeShellScript "tailscale-ssh-assert" ''
        set -u
        export PATH=${lib.makeBinPath [pkgs.coreutils pkgs.tailscale]}
        for _ in $(seq 1 60); do
          if tailscale --socket=/run/tailscale/tailscaled.sock set --ssh 2>/dev/null; then
            echo "tailscale-ssh: RunSSH asserted"
            exit 0
          fi
          sleep 2
        done
        echo "tailscale-ssh: tailscaled socket never came up" >&2
        exit 1
      '';
      log = true;
    };

    # n8n's NixOS state was owned by a systemd DynamicUser (now uid 65534
    # leftovers); give it to the trial's static n8n user. /var/lib/private
    # is 0700 root under systemd - open to 0711 so n8n can traverse. The
    # /var/lib/n8n symlink mirrors systemd's StateDirectory layout:
    # community-package installs under .n8n/nodes reference paths through
    # it, and n8n crashes on any dangling package dir.
    n8n-state = {
      description = "adopt n8n state for static n8n user";
      command = pkgs.writeShellScript "n8n-state" ''
        export PATH=${lib.makeBinPath [pkgs.coreutils]}
        chmod 711 /var/lib/private
        mkdir -p /var/lib/private/n8n
        chown -R n8n:n8n /var/lib/private/n8n
        ln -sfn /var/lib/private/n8n /var/lib/n8n
      '';
      log = true;
    };

    # Parity with mediamtx-update-ip: advertise the public IP for WebRTC.
    mediamtx-env = {
      description = "update mediamtx public IP env";
      conditions = ["net/lo/up"];
      command = pkgs.writeShellScript "mediamtx-env" ''
        export PATH=${lib.makeBinPath [pkgs.coreutils pkgs.curl]}
        ip="$(curl -s --max-time 15 https://api.ipify.org || true)"
        if [ -n "$ip" ]; then
          echo "MTX_WEBRTCADDITIONALHOSTS=$ip" > /run/mediamtx.env
        else
          echo "# no public IP available" > /run/mediamtx.env
        fi
      '';
      log = true;
    };
  };

  finit.services = {
    forgejo = {
      description = "forgejo git hosting";
      user = "forgejo";
      group = "forgejo";
      command = "${pkgs.writeShellScript "forgejo-start" ''
        # Wait for postgres to accept connections; finit has no condition for
        # "socket ready" and forgejo aborts on a refused connection.
        for _ in $(seq 1 60); do
          ${pkgs.postgresql_16}/bin/pg_isready -q -h /run/postgresql && break
          sleep 1
        done
        ${pkgs.postgresql_16}/bin/pg_isready -q -h /run/postgresql || exit 1
        exec ${pkgs.forgejo-lts}/bin/forgejo web
      ''}";
      path = [
        pkgs.forgejo-lts
        pkgs.git
        pkgs.gnupg
        pkgs.coreutils
        pkgs.findutils
        pkgs.gnugrep
        pkgs.gnused
        pkgs.bash
      ];
      environment = {
        HOME = "/var/lib/forgejo";
        FORGEJO_WORK_DIR = "/var/lib/forgejo";
        FORGEJO_CUSTOM = "/var/lib/forgejo/custom";
        FORGEJO__SECURITY__SECRET_KEY__FILE = "/var/lib/forgejo/custom/conf/secret_key";
        FORGEJO__SECURITY__INTERNAL_TOKEN__FILE = "/var/lib/forgejo/custom/conf/internal_token";
        FORGEJO__SERVER__LFS_JWT_SECRET__FILE = "/var/lib/forgejo/custom/conf/lfs_jwt_secret";
        FORGEJO__OAUTH2__JWT_SECRET__FILE = "/var/lib/forgejo/custom/conf/oauth2_jwt_secret";
      };
      conditions = [
        "net/lo/up"
        "service/syslogd/ready"
      ];
      log = true;
    };

    n8n = {
      description = "n8n workflow automation";
      user = "n8n";
      group = "n8n";
      command = "${pkgs.n8n}/bin/n8n";
      path = [pkgs.nodejs];
      environment = {
        # Through the /var/lib/n8n symlink (n8n-state task) for exact
        # systemd parity: package installs then record portable paths.
        HOME = "/var/lib/n8n";
        N8N_USER_FOLDER = "/var/lib/n8n";
        N8N_PORT = "5678";
        N8N_SECURE_COOKIE = "false";
        N8N_DIAGNOSTICS_ENABLED = "false";
        N8N_RUNNERS_MODE = "internal";
        N8N_RUNNERS_BROKER_LISTEN_ADDRESS = "127.0.0.1";
        N8N_RUNNERS_BROKER_PORT = "5679";
        GENERIC_TIMEZONE = config.time.timeZone;
      };
      conditions = [
        "net/lo/up"
        "task/n8n-state/success"
      ];
      log = true;
    };

    mediamtx = {
      description = "mediamtx media server";
      user = "mediamtx";
      group = "mediamtx";
      command = "${pkgs.writeShellScript "mediamtx-start" ''
        if [ -r /run/mediamtx.env ]; then
          set -a
          . /run/mediamtx.env
          set +a
        fi
        exec ${pkgs.mediamtx}/bin/mediamtx ${(pkgs.formats.yaml {}).generate "mediamtx.yaml" {
          webrtc = true;
          webrtcAddress = ":4200";
          webrtcLocalUDPAddress = ":4200";
          paths.all_others = {};
        }}
      ''}";
      conditions = [
        "net/lo/up"
        "task/mediamtx-env/success"
      ];
      log = true;
    };

    tailscaled = {
      description = "tailscale mesh VPN daemon";
      command = "${pkgs.tailscale}/bin/tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/run/tailscale/tailscaled.sock --port=41641";
      path = [
        pkgs.iproute2
        pkgs.iptables
        pkgs.procps
      ];
      conditions = ["net/lo/up"];
      log = true;
    };

    syncthing = {
      description = "syncthing file sync (y0usaf)";
      user = "y0usaf";
      command = "${pkgs.syncthing}/bin/syncthing --config=/home/y0usaf/.config/syncthing --data=/home/y0usaf/.config/syncthing --gui-address=127.0.0.1:8384 --no-browser";
      environment.HOME = "/home/y0usaf";
      conditions = ["net/lo/up"];
      log = true;
    };

    # Reverse proxy for the syncthing GUI over the tailnet
    # (parity with modules/core/services/syncthing-proxy.nix).
    nginx = {
      description = "nginx reverse proxy (syncthing GUI)";
      command = "${pkgs.nginx}/bin/nginx -c ${pkgs.writeText "nginx.conf" ''
        daemon off;
        worker_processes 1;
        pid /run/nginx/nginx.pid;

        events {}

        http {
          access_log off;
          proxy_temp_path /run/nginx/proxy_temp;
          client_body_temp_path /run/nginx/client_body_temp;
          fastcgi_temp_path /run/nginx/fastcgi_temp;
          uwsgi_temp_path /run/nginx/uwsgi_temp;
          scgi_temp_path /run/nginx/scgi_temp;

          map $http_upgrade $connection_upgrade {
            default upgrade;
            ""      close;
          }

          server {
            listen 80;
            server_name syncthing-server;

            location / {
              proxy_pass http://127.0.0.1:8384;
              proxy_http_version 1.1;
              # No Host override: syncthing's GUI host-check only accepts its
              # own gui-address, so the default $proxy_host (127.0.0.1:8384)
              # is exactly right. Forwarding the client Host got 403s.
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection $connection_upgrade;
              proxy_read_timeout 600s;
              proxy_send_timeout 600s;
            }
          }
        }
      ''} -e stderr";
      conditions = ["net/lo/up"];
      log = true;
    };
  };

  environment.systemPackages = [
    pkgs.tailscale # CLI against tailscaled's socket
    pkgs.btrbk
    pkgs.postgresql_16 # psql for poking the live db
  ];
}
