# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "usbhid"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  # Root as tmpfs
  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
    options = [ "defaults" "size=2G" "mode=755" ];
  };

  # Persist volume
  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/f3d25172-f728-4bb6-a14d-f86e97a6a0e7";
    fsType = "btrfs";
    options = [ "subvol=@persist" ];
    neededForBoot = true;
  };

  # Home directory
  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/f3d25172-f728-4bb6-a14d-f86e97a6a0e7";
    fsType = "btrfs";
    options = [ "subvol=@home" ];
  };

  # Special-purpose mounts
  fileSystems."/home/y0usaf/Music" = {
    device = "/dev/disk/by-uuid/f3d25172-f728-4bb6-a14d-f86e97a6a0e7";
    fsType = "btrfs";
    options = [ "subvol=@music" ];
  };

  fileSystems."/home/y0usaf/DCIM" = {
    device = "/dev/disk/by-uuid/f3d25172-f728-4bb6-a14d-f86e97a6a0e7";
    fsType = "btrfs";
    options = [ "subvol=@dcim" ];
  };

  fileSystems."/home/y0usaf/Pictures" = {
    device = "/dev/disk/by-uuid/f3d25172-f728-4bb6-a14d-f86e97a6a0e7";
    fsType = "btrfs";
    options = [ "subvol=@pictures" ];
  };

  fileSystems."/home/y0usaf/.local/share/Steam" = {
    device = "/dev/disk/by-uuid/f3d25172-f728-4bb6-a14d-f86e97a6a0e7";
    fsType = "btrfs";
    options = [ "subvol=@steam" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/5330-BB8D";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/be858002-6caa-4bca-8160-75cc21c1836e";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
