{
  config,
  lib,
  pkgs,
  flakeInputs,
  ...
}: let
  inherit (config.lib.generators) toLua;

  tomoePkg = flakeInputs.tomoe.packages."${pkgs.stdenv.hostPlatform.system}".default;
  # With `user.shell.ekko.open`, the terminal-spawn bind routes through the
  # running mux helper: an attached client requests focus for its existing
  # terminal; cold, the helper falls back to the regular terminal spawn.
  ekkoOpen = config.user.shell.ekko.enable && config.user.shell.ekko.open;
  termSpawn =
    if ekkoOpen
    then "ekko-activate-or-terminal"
    else config.user.defaults.terminal;
  # tomoe has no upstream niri-session-style wrapper binary and no NixOS
  # module, so this flake provides a `tomoe-session` shim that mirrors
  # ~/Dev/tomoe/run-tty.sh but execs the installed package binary. It scopes
  # session env to the compositor process (not leaked via
  # environment.sessionVariables, which would affect every TTY) — the same
  # philosophy as shojiwm's NVIDIA wrapper in ../shojiwm/config.nix.
  # The Lua config body. tomoe's config is a real program (require("wm"),
  # function binds, loops), so it lives here as a Nix string; toLua only
  # serializes the inline value tables (border, displays) — see
  # generators/toLua.nix.
in {
  config = lib.mkIf config.user.ui.tomoe.enable {
    environment.systemPackages = [
      tomoePkg
      (pkgs.writeShellScriptBin "tomoe-session" ''
        export XDG_CURRENT_DESKTOP=tomoe
        export XDG_SESSION_TYPE=wayland
        export NIXOS_OZONE_WL=1
        export QT_QPA_PLATFORM=wayland
        export ELECTRON_OZONE_PLATFORM_HINT=wayland
        export GDK_BACKEND=wayland
        export SDL_VIDEODRIVER=wayland,x11
        export CLUTTER_BACKEND=wayland
        export XCURSOR_THEME=${config.user.ui.cursor.package.xcursorThemeName}
        export XCURSOR_SIZE=${toString config.user.appearance.xcursorSize}
        export TOMOE_PORTAL_CHOOSER="''${TOMOE_PORTAL_CHOOSER:-$HOME/.config/scripts/portal-chooser.sh}"

        ${lib.optionalString config.hardware.nvidia.enable ''
          export WLR_NO_HARDWARE_CURSORS=1
          export LIBVA_DRIVER_NAME=nvidia
        ''}
        # No GBM_BACKEND / __EGL_VENDOR_LIBRARY_FILENAMES / __GLX_VENDOR_LIBRARY_NAME
        # here: forcing the NVIDIA-only EGL vendor hides Mesa's EGL_EXT_device_query
        # from the glvnd client-extension union, which smithay requires to probe the
        # render device — tomoe then finds no renderer on ANY GPU and comes up with
        # zero outputs (black screen). run-tty.sh never set these and works.
        cd "$HOME"
        exec ${lib.getExe tomoePkg} --backend tty "$@"
      '')
      pkgs.grim
      pkgs.slurp
      pkgs.wl-clipboard-rs
      pkgs.jq
      pkgs.swaybg
      pkgs.xwayland-satellite
    ];

    # The tomoe package's postInstall already installs the tomoe-session.target
    # (BindsTo graphical-session.target — how the compositor activates the
    # graphical session), the tomoe.portal / tomoe-portals.conf, and the
    # D-Bus service file for the portal backend into system dirs.
    xdg.portal = {
      enable = true;
      extraPortals = [pkgs.xdg-desktop-portal-gtk];
      config.tomoe.default = ["gtk"];
    };

    manzil.users."${config.user.name}".files.".config/tomoe/init.lua" = {
      text =
        ''
          -- Generated by ~/nixos (modules/desktop/session/ui/tomoe/config.nix).
          -- The compositor core is mechanism-only; ALL window management below
          -- comes from the `wm` module — Lua code built on the same public API
          -- your config uses. Don't require it and write your own to replace the
          -- WM wholesale.

          local wm = require("wm")
          wm.gaps = 8
          -- wm.lua ships workspace_count = 9, but no binds below ever call
          -- wm.switch / wm.move_focused, so the session never leaves workspace 1:
          -- the deck layout is the whole session. Per-workspace state in `visible`
          -- and the global `column` table just stay single-entry in practice.

          tomoe.settings {
            -- Alt, matching the niri setup this replaced (niri/input.nix mod-key).
            mod = "alt",
            border = ${toLua {
            width = 2;
            focused = "#7aa2f7";
            unfocused = "#3b4261";
          }},
                -- NVIDIA: a fenced frame queued to KMS before its render completes
                -- hangs the driver (whole-session freeze, niri discussion #3777);
                -- wait for the render CPU-side instead.
                wait_for_frame_completion = true,
          ${lib.optionalString (config.user.ui.tomoe.displays != {}) ''
              displays = ${toLua config.user.ui.tomoe.displays},''}
          }

          -- ─── Processes ───────────────────────────────────────────────────────────────
          tomoe.process.once("xwayland-satellite", { command = { "${lib.getExe pkgs.xwayland-satellite}" } })
          tomoe.process.once("swaybg", { command = {
            "sh", "-c",
            "swaybg -i $(find ${config.user.paths.wallpapers.static.path} -type f | shuf -n 1) -m fill",
          } })
          -- nur is a layer-shell client, so it runs the same under tomoe as under
          -- niri. As a service, tomoe restarts it when it exits or crashes (1 Hz
          -- supervision). The watchdog covers the case tomoe can't see — a frozen
          -- nur that's still alive — by probing its IPC and killing it on hang,
          -- which turns a freeze into an exit the service policy handles.
          ${lib.optionalString config.user.ui.nur.enable ''
              tomoe.process.service("nur", { command = { "${lib.getExe config.user.ui.nur.package}" }, restart = "on_exit" })''}
          -- TODO: nur-watchdog has no flake input; add one to re-enable.
          -- tomoe.process.service("nur-watchdog", { command = { "nur-watchdog" }, restart = "on_exit" })
          -- moonshell (nur's successor) is also a plain layer-shell client; same
          -- supervision story, no watchdog needed yet — it has no GPU stack to
          -- freeze and tomoe's on_exit restart covers crashes.
          ${lib.optionalString (config.user.ui.moonshell.enable or false) ''
              tomoe.process.service("moonshell", { command = { "${lib.getExe config.user.ui.moonshell.package}" }, restart = "on_exit" })''}

          -- ─── Layout: two 16:9 deck columns ───────────────────────────────────────────
          -- The screen splits into a left and a right half-column; on 32:9 each
          -- half is exactly 16:9. Each column is a deck: its front window fills
          -- the half and the rest stay mapped one slot above/below it, so J/K can
          -- animate the whole stack vertically instead of hide/show swapping.
          -- wm's event hooks call arrange through the module table, so
          -- reassigning wm.arrange swaps the layout everywhere.
          local column = {} -- window id -> "left" | "right", persists across workspaces
          local visible = {} -- workspace -> { left = id, right = id }: each deck's front
          local floating = {} -- window id -> true: stays in its workspace, outside tiling

          -- Mod+r cycles the column split: 16:9+16:9 → 21:9+11:9 → 11:9+21:9.
          -- On the 32:9 screen, these are fractions of the total usable width:
          -- 21/32 = 0.65625, 11/32 = 0.34375.
          local ratios = { 0.5, 21/32, 11/32 }
          local ratio_idx = 1
          local ratio = ratios[1]

          local function vis()
            visible[wm.active] = visible[wm.active] or {}
            return visible[wm.active]
          end

          -- Partition a workspace's tiled windows into ordered column lists,
          -- assigning any new window to the focused window's column so a newly
          -- spawned window stacks in the deck you're working in, not the opposite
          -- one. With no tiled focused window, fall back to the emptier column
          -- (tie: left). A new window jumps to the front of its deck (wm focuses
          -- it on open).
          local function split_columns(wins)
            local left, right = {}, {}
            local f = tomoe.focused_window()
            local fside = f and column[f:id()]
            for _, win in ipairs(wins) do
              local id = win:id()
              if not column[id] then
                if fside == "left" or fside == "right" then
                  column[id] = fside
                elseif #left ~= #right then
                  column[id] = #left < #right and "left" or "right"
                else
                  column[id] = "left"
                end
                vis()[column[id]] = id
              end
              table.insert(column[id] == "left" and left or right, win)
            end
            return left, right
          end

          local function tiled_windows()
            local wins, full, floats = {}, {}, {}
            for _, win in ipairs(wm.workspaces[wm.active]) do
              local id = win:id()
              local rules = tomoe.rules_for(win)
              -- Classify rule-floated windows before split_columns sees them:
              -- briefly tiling then removing a transient corrupts the deck's
              -- visible id and makes that column jump back to its first window.
              if rules.floating then
                floating[id] = true
              end
              if wm.fullscreen[id] then
                table.insert(full, win)
              elseif floating[id] then
                table.insert(floats, win)
              else
                table.insert(wins, win)
              end
            end
            return wins, full, floats
          end

          -- Floating windows stay above the tiled deck; fullscreen stays above both.
          local function raise_untiled(floats, full)
            for _, win in ipairs(floats) do
              win:show()
              win:raise()
            end
            for _, win in ipairs(full) do
              win:show()
              win:raise()
            end
          end

          -- Alt+O toggles a flat grid: every tiled window on the workspace shown
          -- at once, equal-sized, gaps preserved (no 16:9 letterboxing, no deck
          -- hiding). Off again on the next press. wm.arrange reads this flag, so
          -- the layout follows focus/workspace switches until it's toggled back.
          wm.grid = false

          function wm.arrange()
            local area = tomoe.usable_area()
            local wins, full, floats = tiled_windows()
            local g = wm.gaps
            local x, y = area.x + g, area.y + g
            local w, h = area.w - 2 * g, area.h - 2 * g
            if wm.grid then
              local n = #wins
              if n == 0 then
                raise_untiled(floats, full)
                return
              end
              -- Fit n windows into the nearest-square grid (cols >= rows), each
              -- cell equal-sized. ceil(n/cols) rows so the last row never spills.
              local cols = math.ceil(math.sqrt(n))
              local rows = math.ceil(n / cols)
              local cw = math.floor((w - (cols - 1) * g) / cols)
              local ch = math.floor((h - (rows - 1) * g) / rows)
              for i, win in ipairs(wins) do
                local idx = i - 1
                local r = math.floor(idx / cols)
                local c = idx % cols
                win:set_geometry(
                  x + c * (cw + g),
                  y + r * (ch + g),
                  cw, ch
                )
                win:show()
              end
              raise_untiled(floats, full)
              return
            end
            local left_cw = math.floor((w - g) * ratio)
            local right_cw = w - g - left_cw
            local left, right = split_columns(wins)
            local v = vis()
            local function place(col, side, cx, cw)
              if #col == 0 then
                v[side] = nil
                return
              end
              local front_idx = 1
              for i, win in ipairs(col) do
                if win:id() == v[side] then
                  front_idx = i
                  break
                end
              end
              local front = col[front_idx]
              local stride = h + g
              v[side] = front:id()
              for i, win in ipairs(col) do
                win:set_geometry(
                  cx,
                  y + (i - front_idx) * stride,
                  cw, h
                )
                win:show()
              end
              front:raise()
            end
            place(left, "left", x, left_cw)
            place(right, "right", x + left_cw + g, right_cw)
            raise_untiled(floats, full)
          end

          -- H/L: focus the left/right deck's front window.
          local function focus_column(side)
            local left, right = split_columns(tiled_windows())
            local col = side == "left" and left or right
            local id = vis()[side]
            for _, win in ipairs(col) do
              if win:id() == id then
                win:focus()
                return
              end
            end
            if col[1] then
              col[1]:focus()
            end
          end

          -- J/K: scroll the focused deck down/up (wraps), revealing and focusing
          -- the next window in the column.
          local function focus_vert(dir)
            local f = tomoe.focused_window()
            local side = f and column[f:id()]
            if not side then
              return
            end
            local left, right = split_columns(tiled_windows())
            local col = side == "right" and right or left
            for i, win in ipairs(col) do
              if win:id() == vis()[side] then
                local target = col[((i - 1 + dir) % #col) + 1]
                vis()[side] = target:id()
                wm.arrange()
                target:focus()
                return
              end
            end
          end

          -- Shift+J/K: move the focused window down/up within its deck's scroll
          -- order, by swapping with its column neighbor in the workspace order.
          local function move_vert(dir)
            local f = tomoe.focused_window()
            local side = f and column[f:id()]
            if not side then
              return
            end
            local wins = wm.workspaces[wm.active]
            local idxs, mine = {}, nil
            for i, win in ipairs(wins) do
              if column[win:id()] == side and not wm.fullscreen[win:id()] then
                table.insert(idxs, i)
                if win:id() == f:id() then
                  mine = #idxs
                end
              end
            end
            local other = mine and mine + dir
            if not other or other < 1 or other > #idxs then
              return
            end
            local a, b = idxs[mine], idxs[other]
            wins[a], wins[b] = wins[b], wins[a]
            wm.arrange()
          end

          -- Shift+H/L: swap the two columns wholesale (deck fronts included).
          local function swap_columns()
            for _, win in ipairs(wm.workspaces[wm.active]) do
              local id = win:id()
              if column[id] then
                column[id] = column[id] == "left" and "right" or "left"
              end
            end
            local v = vis()
            v.left, v.right = v.right, v.left
            wm.arrange()
          end

          -- [ / ]: send the focused window to the left/right column, where it
          -- becomes the deck front. If it was the old deck's front, reveal the
          -- next window in that deck rather than resetting to its first entry.
          local function move_to_column(side)
            local f = tomoe.focused_window()
            if not f or wm.fullscreen[f:id()] or floating[f:id()] then
              return
            end
            local id = f:id()
            local v = vis()
            local prev = column[id]
            if prev and prev ~= side and v[prev] == id then
              local left, right = split_columns(tiled_windows())
              local old = prev == "left" and left or right
              v[prev] = nil
              for i, win in ipairs(old) do
                if win:id() == id and #old > 1 then
                  -- Deck navigation wraps, so popping the bottom window reveals
                  -- the top one just as focus_vert(1) would.
                  v[prev] = old[(i % #old) + 1]:id()
                  break
                end
              end
            end
            column[id] = side
            v[side] = id
            wm.arrange()
          end

          local function toggle_floating()
            local win = tomoe.focused_window()
            if not win then
              return
            end
            local id = win:id()
            -- Niri's floating transition normalizes fullscreen first. Do the
            -- same here: a fullscreen client becomes tiled on the first press
            -- instead of making Super+Space a no-op.
            if wm.fullscreen[id] or win:is_fullscreen() then
              floating[id] = nil
              wm.set_fullscreen(win, false)
              win:focus()
              return
            end
            if floating[id] then
              floating[id] = nil
              wm.arrange()
            else
              floating[id] = true
              wm.arrange()
              local area = tomoe.usable_area()
              local w = math.floor(area.w * 0.6)
              local h = math.floor(area.h * 0.6)
              win:set_geometry(
                area.x + math.floor((area.w - w) / 2),
                area.y + math.floor((area.h - h) / 2),
                w, h)
            end
            win:focus()
          end

          tomoe.on_reload("deck-floating", function()
            local ids = {}
            for id in pairs(floating) do
              ids[#ids + 1] = id
            end
            return ids
          end, function(ids)
            floating = {}
            for _, id in ipairs(ids or {}) do
              if tomoe.window(id) then
                floating[id] = true
              end
            end
            wm.arrange()
          end)

          -- Click-to-focus or wm's close-refocus can land on a deck-offscreen
          -- window; bring it to the front of its deck. Untiled windows (the
          -- floating launcher) are skipped. Also keep a one-step focus history:
          -- the close hook below needs to know who was focused before wm's
          -- close-refocus already moved focus.
          local last_focus = {}
          local function find_tiled(id)
            if floating[id] then
              return
            end
            for _, win in ipairs(wm.workspaces[wm.active]) do
              if win:id() == id then
                return win
              end
            end
          end
          tomoe.on_focus_change(function(win)
            if not win then
              return
            end
            local id = win:id()
            if id ~= last_focus.cur then
              last_focus.prev, last_focus.cur = last_focus.cur, id
            end
            local side = column[id]
            if side and not wm.fullscreen[id] and find_tiled(id) and vis()[side] ~= id then
              vis()[side] = id
              wm.arrange()
            end
          end)

          -- wm's close hook (runs first) refocuses the flat-list-last window,
          -- which may sit in the other deck. If the closed window was the focused
          -- deck front, pull focus back to whatever that deck revealed instead.
          -- Also drop the column assignment so reused ids start fresh.
          tomoe.on_window_close(function(win)
            local id = win:id()
            local side = column[id]
            column[id] = nil
            floating[id] = nil
            if side and id == last_focus.prev then
              local front = vis()[side] and find_tiled(vis()[side])
              if front then
                front:focus()
              end
            end
          end)

          -- ─── Binds (mirroring niri/keybindings.nix; Mod = Alt) ───────────────────────
          tomoe.bind("Mod+t", function() tomoe.spawn("${termSpawn}") end, "Spawn Terminal")
          tomoe.bind("Super+r", function() tomoe.spawn("foot --app-id=launcher ~/.config/scripts/tui-launcher.sh") end, "Run an Application")
          tomoe.bind("Mod+e", function() tomoe.spawn("pcmanfm") end, "File Manager")
          tomoe.bind("Super+Shift+o", function() tomoe.spawn("foot -e nvim") end, "Editor")
          tomoe.bind("Mod+q", wm.close_focused, "Close Window")
          tomoe.bind("Mod+f", wm.toggle_fullscreen, "Toggle Fullscreen")
          tomoe.bind("Super+space", toggle_floating, "Toggle Floating")
          tomoe.bind("Mod+Shift+e", "quit")
          tomoe.bind("Mod+Shift+slash", "show-hotkey-overlay")

          -- ─── Focus / movement (HJKL over the two columns) ────────────────────────────
          tomoe.bind("Mod+h", function() focus_column("left") end, "Focus Left Column")
          tomoe.bind("Mod+l", function() focus_column("right") end, "Focus Right Column")
          tomoe.bind("Mod+j", function() focus_vert(1) end, "Scroll Deck Down")
          tomoe.bind("Mod+k", function() focus_vert(-1) end, "Scroll Deck Up")
          tomoe.bind("Mod+Shift+h", swap_columns, "Swap Columns")
          tomoe.bind("Mod+Shift+l", swap_columns)
          tomoe.bind("Mod+Shift+j", function() move_vert(1) end, "Move Window Down")
          tomoe.bind("Mod+Shift+k", function() move_vert(-1) end, "Move Window Up")
          tomoe.bind("Mod+bracketleft", function() move_to_column("left") end, "Move Window to Left Column")
          tomoe.bind("Mod+bracketright", function() move_to_column("right") end, "Move Window to Right Column")
          tomoe.bind("Mod+o", function() wm.grid = not wm.grid; wm.arrange() end, "Toggle Even Grid")
          tomoe.bind("Mod+r", function()
            ratio_idx = ratio_idx % #ratios + 1
            ratio = ratios[ratio_idx]
            wm.arrange()
          end, "Cycle Column Split (16:9+16:9 / 21:9+11:9 / 11:9+21:9)")

          -- ─── Apps ────────────────────────────────────────────────────────────────────
          tomoe.bind("Mod+1", function() tomoe.spawn("cursor") end)
          tomoe.bind("Mod+2", function() tomoe.spawn("librewolf") end)
          tomoe.bind("Mod+3", function() tomoe.spawn("discord") end)
          tomoe.bind("Mod+4", function() tomoe.spawn("steam") end)
          tomoe.bind("Mod+5", function() tomoe.spawn("obs") end)

          -- ─── Screenshots / wallpaper ─────────────────────────────────────────────────
          tomoe.bind("Mod+g", "screenshot", "Screenshot")
          tomoe.bind("Mod+Shift+g", "screenshot-screen", "Screenshot Screen")
          tomoe.bind("Mod+Shift+c", function() tomoe.spawn("killall swaybg; swaybg -i $(find ${config.user.paths.wallpapers.static.path} -type f | shuf -n 1) -m fill &") end, "Random Wallpaper")

          -- ─── Media ───────────────────────────────────────────────────────────────────
          tomoe.bind("XF86AudioRaiseVolume", function() tomoe.spawn("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+") end)
          tomoe.bind("XF86AudioLowerVolume", function() tomoe.spawn("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-") end)
          tomoe.bind("XF86AudioMute", function() tomoe.spawn("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle") end)
          tomoe.bind("XF86AudioPlay", function() tomoe.spawn("playerctl play-pause") end)
          tomoe.bind("XF86AudioNext", function() tomoe.spawn("playerctl next") end)
          tomoe.bind("XF86AudioPrev", function() tomoe.spawn("playerctl previous") end)
        ''
        + lib.optionalString (config.user.ui.tomoe.extraConfig != "") "\n-- ─── host extraConfig ────────────────────────────────────────────────────────\n${config.user.ui.tomoe.extraConfig}\n";
    };
  };
}
