{
  config,
  lib,
  pkgs,
  flakeInputs,
  ...
}: let
  inherit (config.lib.generators) toLua;

  tomoePkg = flakeInputs.tomoe.packages."${pkgs.stdenv.hostPlatform.system}".default;

  # tomoe has no upstream niri-session-style wrapper binary and no NixOS
  # module, so this flake provides a `tomoe-session` shim that mirrors
  # ~/Dev/tomoe/run-tty.sh but execs the installed package binary. It scopes
  # session env to the compositor process (not leaked via
  # environment.sessionVariables, which would affect every TTY) — the same
  # philosophy as shojiwm's NVIDIA wrapper in ../shojiwm/config.nix.
  tomoeSession = pkgs.writeShellScriptBin "tomoe-session" ''
    export XDG_CURRENT_DESKTOP=tomoe
    export XDG_SESSION_TYPE=wayland
    export NIXOS_OZONE_WL=1
    export QT_QPA_PLATFORM=wayland
    export ELECTRON_OZONE_PLATFORM_HINT=wayland
    export GDK_BACKEND=wayland
    export SDL_VIDEODRIVER=wayland,x11
    export CLUTTER_BACKEND=wayland
    export XCURSOR_THEME=${config.user.ui.cursor.package.xcursorThemeName}
    export XCURSOR_SIZE=${toString config.user.appearance.xcursorSize}
    export TOMOE_PORTAL_CHOOSER="''${TOMOE_PORTAL_CHOOSER:-$HOME/.config/scripts/portal-chooser.sh}"
    ${lib.optionalString config.hardware.nvidia.enable ''
      export WLR_NO_HARDWARE_CURSORS=1
      export GBM_BACKEND=nvidia-drm
      export __GLX_VENDOR_LIBRARY_NAME=nvidia
      export __EGL_VENDOR_LIBRARY_FILENAMES=/run/opengl-driver/share/glvnd/egl_vendor.d/10_nvidia.json
      export LIBVA_DRIVER_NAME=nvidia
    ''}
    cd "$HOME"
    exec ${lib.getExe tomoePkg} --backend tty "$@"
  '';

  # The Lua config body. tomoe's config is a real program (require("wm"),
  # function binds, loops), so it lives here as a Nix string; toLua only
  # serializes the inline value tables (border, displays) — see
  # generators/toLua.nix.
  initLua = ''
    -- Generated by ~/nixos (modules/desktop/session/ui/tomoe/config.nix).
    -- The compositor core is mechanism-only; ALL window management below
    -- comes from the `wm` module — Lua code built on the same public API
    -- your config uses. Don't require it and write your own to replace the
    -- WM wholesale.

    local wm = require("wm")
    wm.gaps = 8

    tomoe.settings {
      mod = "super",
      border = ${toLua {
      width = 2;
      focused = "#7aa2f7";
      unfocused = "#3b4261";
    }},${lib.optionalString (config.user.ui.tomoe.displays != {}) ''
        displays = ${toLua config.user.ui.tomoe.displays},''}
    }

    -- ─── Processes ───────────────────────────────────────────────────────────────
    tomoe.process.once("xwayland-satellite", { command = { "${lib.getExe pkgs.xwayland-satellite}" } })
    tomoe.process.once("swaybg", { command = {
      "sh", "-c",
      "swaybg -i $(find ${config.user.paths.wallpapers.static.path} -type f | shuf -n 1) -m fill",
    } })

    -- ─── Launch / close ──────────────────────────────────────────────────────────
    tomoe.bind("Mod+Return", function() tomoe.spawn("foot") end, "Spawn foot")
    tomoe.bind("Mod+d", function() tomoe.spawn("fuzzel") end, "Run an Application")
    tomoe.bind("Mod+q", wm.close_focused, "Close Window")
    tomoe.bind("Mod+f", wm.toggle_fullscreen, "Toggle Fullscreen")
    tomoe.bind("Mod+Shift+e", "quit")
    tomoe.bind("Mod+Shift+slash", "show-hotkey-overlay")

    -- ─── Focus ───────────────────────────────────────────────────────────────────
    tomoe.bind("Mod+j", wm.focus_next, "Focus Next Window")
    tomoe.bind("Mod+k", wm.focus_prev, "Focus Previous Window")

    -- ─── Workspaces ──────────────────────────────────────────────────────────────
    for i = 1, wm.workspace_count do
      tomoe.bind("Mod+" .. i, function() wm.switch(i) end,
        i == 1 and "Switch to Workspace 1-9" or nil)
      tomoe.bind("Mod+Shift+" .. i, function() wm.move_focused(i) end,
        i == 1 and "Move Window to Workspace 1-9" or nil)
    end
  '';
in {
  config = lib.mkIf config.user.ui.tomoe.enable {
    environment.systemPackages = [
      tomoePkg
      tomoeSession
      pkgs.grim
      pkgs.slurp
      pkgs.wl-clipboard-rs
      pkgs.jq
      pkgs.swaybg
      pkgs.xwayland-satellite
    ];

    # The tomoe package's postInstall already installs the tomoe-session.target
    # (BindsTo graphical-session.target — how the compositor activates the
    # graphical session), the tomoe.portal / tomoe-portals.conf, and the
    # D-Bus service file for the portal backend into system dirs.
    xdg.portal = {
      enable = true;
      extraPortals = [pkgs.xdg-desktop-portal-gtk];
      config.tomoe.default = ["gtk"];
    };

    manzil.users."${config.user.name}".files.".config/tomoe/init.lua" = {
      text =
        initLua
        + lib.optionalString (config.user.ui.tomoe.extraConfig != "") "\n-- ─── host extraConfig ────────────────────────────────────────────────────────\n${config.user.ui.tomoe.extraConfig}\n";
    };
  };
}
